import { Label } from "@radix-ui/react-dropdown-menu";
import { COACH_CATEGORIES } from "../../config";
import { CollectionConfig } from "payload/types";

const focusAreaOptions = [
  "Character Development",
  "Story Structure",
  "World-building",
  "Script Review",
  "Scripting",
  "Visual Storytelling",
  "Balancing Dialogue and Art",
  "Plot Development",
  "Writing Style and Voice",
  "Conflict Resolution",
  "Building Tension and Suspense",
  "Resrach Methods",
  "Structuring Articles/Essays",
  "Crafting introductions/conclusions",
  "Adapting Stories for Screen",
  "Collaborative Scriptwriting",
  "Manga Page Layout",
  "Charecter Design for Manga",
  "Balancing Action and Dialogue",
  "Investigative Journalism",
  "Writing Compelling Headlines",
  "Interview Techniques",
  "Fact-Checking and Accuracy",
  "Covering Sensitive Topics Responsibly",
  "Loglines",
  // Add more options as needed
];

const languageOptions = [
  "English",
  "Spanish",
  "French",
  "German",
  "Chinese",
  "Japanese",
  "Korean",
  "Arabic",
  "Russian",
  "Italian",
  "Portuguese",
  "Dutch",
  "Swedish",
  "Turkish",
  "Hindi",
  "Bengali",
  "Urdu",
  "Persian",
  "Swahili",
  "Vietnamese",
  "Indonesian",
  "Malay",
  "Thai",
  "Greek",
  "Hebrew",
  "Czech",
  "Polish",
  "Romanian",
  "Hungarian",
  "Finnish",
  "Danish",
  "Norwegian",
  "Icelandic",
  "Slovak",
  "Slovenian",
  "Croatian",
  "Bulgarian",
  "Serbian",
  "Macedonian",
  "Albanian",
  "Latvian",
  "Lithuanian",
  "Estonian",
  "Georgian",
  "Armenian",
  "Azerbaijani",
  "Kazakh",
  "Uzbek",
  "Yoruba",
];

const pinnedOptions = [
  "Achievement",
  "Publication",
  "Contribution",
  "Milestone",
  "Media Feature",
];

const freeSessionDurationOptions = ["15", "30"];

// const pinnedOptionsWithEmojis = {
//   ACHIEVEMENT: "🏆 Achievement:",
//   PUBLICATION: "📚 Publication:",
//   CONTRIBUTION: "🌟 Contribution:",
//   MILESTONE: "🎉 Milestone:",
//   MEDIA_FEATURE: "📰 Media Feature:",
// };

export const Coaches: CollectionConfig = {
  slug: "coaches",
  admin: {
    useAsTitle: "name",
  },
  access: {},
  fields: [
    {
      name: "user",
      type: "relationship",
      relationTo: "users",
      required: true,
      hasMany: false,
      admin: {
        condition: () => false,
      },
    },
    {
      name: "name",
      label: "Name",
      type: "text",
      required: true,
    },

    {
      name: "aboutMe",
      label: "About me",
      type: "richText",
      required: true,
    },
    {
      name: "hourlyRate",
      label: "Hourly rate!",
      type: "number",
      min: 0,
      max: 100,
      required: true,
    },
    {
      name: "category",
      label: "Category",
      type: "select",
      hasMany: true,
      options: COACH_CATEGORIES.map(({ label, value }) => ({ label, value })),
      required: true,
    },
    {
      name: "profilePicture",
      label: "Profile Picture",
      type: "array",
      required: true,
      fields: [
        {
          name: "image",
          type: "upload",
          relationTo: "media",
        },
      ],
    },
    {
      name: "headline",
      label: "Headline",
      type: "text",
      required: true,
    },
    {
      name: "introvideo",
      label: "Intro Video",
      type: "upload",
      relationTo: "media",
      required: false,
    },
    {
      name: "language",
      label: "Language",
      type: "select",
      hasMany: true,
      options: languageOptions,
    },
    {
      name: "focusAreas",
      label: "Focus areas",
      type: "select",
      hasMany: true,
      options: focusAreaOptions,
    },
    {
      name: "workHistory",
      label: "Work History",
      type: "array",
      minRows: 1,
      maxRows: 5,
      fields: [
        {
          name: "typeOfWork",
          label: "Type of Work",
          type: "select",
          options: [
            { label: "Worked For", value: "workedFor" },
            { label: "Worked On", value: "workedOn" },
            { label: "Works At", value: "worksAt" },
          ],
          required: true,
        },
        {
          name: "companyName",
          label: "Company Name",
          type: "text",
          required: true,
        },
        {
          name: "role",
          label: "Job title",
          type: "text",
          required: true,
        },
        {
          name: "endDatePresent",
          label: "End Date (Present)",
          type: "checkbox",
          defaultValue: false,
        },
        {
          name: "startDate",
          label: "Start Date",
          type: "date",
          required: true,
        },
        {
          name: "endDate",
          label: "End Date",
          type: "date",
          required: false,
        },
      ],
    },

    {
      name: "FAQs",
      label: "FAQ's",
      type: "array",
      minRows: 2,
      maxRows: 6,
      fields: [
        {
          name: "faqQuestion",
          label: "FAQ Question",
          type: "text",
          required: true,
        },
        {
          name: "faqAnswer",
          label: "FAQ Answer",
          type: "text",
          required: true,
        },
      ],
    },
    {
      name: "pinnedHighlights",
      label: "Pinned Highlights",
      type: "array",
      minRows: 1,
      maxRows: 20,
      fields: [
        {
          name: "PinnedHighlightType",
          label: "Pinned Highlight",
          type: "select",
          options: pinnedOptions,
          required: true,
        },
        {
          name: "highlight",
          label: "Highlight",
          type: "text",
          required: true,
        },
      ],
    },
    {
      name: "freeIntroductionOption",
      label: "Free Introduction Option",
      type: "array",
      fields: [
        {
          name: "freeIntroChoice",
          label: "Click me to offer free introduction sessions",
          type: "checkbox",
          defaultValue: false,
        },
        {
          name: "freeSessionDuration",
          label: "Free Session Duration",
          type: "select",
          options: [
            { label: "15 minutes", value: "15" },
            { label: "30 minutes", value: "30" },
          ],
        },
      ],
    },
    {
      name: "portfolios",
      label: "Portfolios",
      type: "array",
      minRows: 1,
      fields: [
        {
          name: "title",
          label: "Title",
          type: "text",
          required: true,
        },
        {
          name: "description",
          label: "Description",
          type: "textarea",
          required: true,
        },
        {
          name: "media",
          label: "Media",
          type: "upload",
          relationTo: "media",
        },
        {
          name: "link",
          label: "Link",
          type: "text",
        },
      ],
    },
    //TP
    {
      name: "coachingPackages",
      label: "Coaching Packages",
      type: "array",
      minRows: 1,
      maxRows: 15,
      fields: [
        {
          name: "title",
          label: "Title",
          type: "text",
          required: true,
        },
        {
          name: "coachingPackagePicture",
          label: "Picture",
          type: "upload",
          relationTo: "media",
          required: true,
        },
        {
          name: "explainerVideo",
          label: "Explainer Video",
          type: "upload",
          relationTo: "media",
          required: false,
        },
        {
          name: "description",
          label: "Description",
          type: "textarea",
          required: true,
        },
        {
          name: "price",
          label: "Price",
          type: "number",
          min: 1,
          max: 1000,
          required: true,
        },
        {
          name: "time",
          label: "Duration in hours",
          type: "number",
          min: 1,
          max: 10,
          required: true,
        },
        {
          name: "numberOfSessions",
          label: "Number of Sessions",
          type: "number",
          required: true,
        },
        {
          name: "focusarea",
          label: "Focus Area",
          type: "select",
          hasMany: true,
          options: focusAreaOptions,
          required: true,
        },
      ],
    },
    {
      name: "whyICoach",
      label: "Express your coaching why",
      type: "textarea",
      required: false,
    },
    {
      name: "approvedForSale",
      label: "Coach status",
      type: "select",
      defaultValue: "pending",
      access: {
        create: ({ req }) => req.user.role === "admin",
        read: ({ req }) => req.user.role === "admin",
        update: ({ req }) => req.user.role === "admin",
      },
      options: [
        {
          label: "pending verification",
          value: "pending",
        },
        {
          label: "Approved",
          value: "approved",
        },
        {
          label: "Denied",
          value: "denied",
        },
      ],
    },
    {
      name: "priceId",
      access: {
        create: () => false,
        read: () => false,
        update: () => false,
      },
      type: "text",
      admin: {
        hidden: true,
      },
    },
    {
      name: "stripeId",
      access: {
        create: () => false,
        read: () => false,
        update: () => false,
      },
      type: "text",
      admin: {
        hidden: true,
      },
    },
  ],
};
